project = 'lua-fort'
title = 'lua-fort docs v1.1.0'
description = 'An ASCII formatted table generating library'
format = 'discount'
backtick_references = true
file = 'doc.lua'
dir = 'docs'
topics = {'README.md', 'CHANGELOG.md'}
style = '!fixed'
kind_names = {topic = 'Manual', script = 'Programs'}
wrap = true
sort = false
examples = {'./examples'}
use_markdown_titles = true
template = true

tparam_alias('ftable', 'ftable')
tparam_alias('userdata', 'userdata')
