project = 'lua-fort'
title = 'lua-fort documentation v0.1.0'
description = 'An ASCII formatted table generating library'
format = 'discount'
backtick_references = false
file = 'src/fort.lua'
dir = 'build'
readme = 'README.md'
style = '!fixed'
kind_names = {topic = 'Manual', script = 'Programs'}
wrap = true
sort = false
examples = {'./examples'}
tparam_alias('ftable', 'ftable')
tparam_alias('userdata', 'userdata')
