name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6" "5.4.3"]

    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: build
        run: |
          luarocks install busted
          luarocks make

